import re

with open(r'C:\Users\chris\ciscolearn\www\index.html', 'r', encoding='utf-8') as f:
    content = f.read()

new_quiz = r"""const QUIZ_QS=[
  // Easy (diff:1)
  {cat:'subnetting',diff:1,q:'How many usable hosts does a /28 subnet provide?',opts:['14','16','30','12'],ans:0,explain:'2⁴ = 16 total − 2 (network + broadcast) = 14 usable hosts.'},
  {cat:'subnetting',diff:1,q:'What is the broadcast address of 10.0.0.0/30?',opts:['10.0.0.1','10.0.0.2','10.0.0.3','10.0.0.4'],ans:2,explain:'/30 has 4 addresses: .0 (network), .1, .2 (hosts), .3 (broadcast).'},
  {cat:'subnetting',diff:1,q:'Which subnet mask equals /25?',opts:['255.255.255.0','255.255.255.128','255.255.255.192','255.255.254.0'],ans:1,explain:'/25 = 25 ones = 255.255.255.128.'},
  {cat:'subnetting',diff:1,q:'What does the /prefix notation (CIDR) represent?',opts:['The number of host bits','The number of 1-bits in the subnet mask','The number of subnets','The number of broadcast domains'],ans:1,explain:'CIDR prefix = number of consecutive 1-bits in the subnet mask. /24 = 24 ones = 255.255.255.0.'},
  {cat:'vlan',diff:1,q:'What command assigns a switch port to VLAN 20?',opts:['switchport vlan 20','switchport access vlan 20','vlan access 20','set vlan 20'],ans:1,explain:'"switchport access vlan <id>" assigns the port after setting it to access mode.'},
  {cat:'vlan',diff:1,q:'What is the purpose of a trunk port?',opts:['Carry one VLAN only','Connect to end devices','Carry multiple VLANs between switches','Block unauthorized VLANs'],ans:2,explain:'Trunk ports use 802.1Q tagging to carry multiple VLANs on one link.'},
  {cat:'vlan',diff:1,q:'Which protocol is used for VLAN tagging on trunk links?',opts:['ISL','802.1Q','802.3','CDP'],ans:1,explain:'IEEE 802.1Q is the standard for VLAN tagging. ISL is Cisco-proprietary and deprecated.'},
  {cat:'vlan',diff:1,q:'What is the default VLAN on a Cisco switch access port?',opts:['VLAN 0','VLAN 1','VLAN 100','VLAN 1002'],ans:1,explain:'All Cisco switch ports belong to VLAN 1 by default. VLAN 1 is also the default native VLAN on trunk ports.'},
  {cat:'routing',diff:1,q:'What does "gateway of last resort" mean?',opts:['The fastest route','The default route for unmatched traffic','The lowest-metric route','The directly connected route'],ans:1,explain:'A default route (0.0.0.0/0) is used when no more specific route exists.'},
  {cat:'routing',diff:1,q:'Which command adds a default route via 10.0.0.1?',opts:['ip route default 10.0.0.1','ip route 0.0.0.0 0.0.0.0 10.0.0.1','ip default-route 10.0.0.1','route 0.0.0.0/0 10.0.0.1'],ans:1,explain:'"ip route 0.0.0.0 0.0.0.0 <next-hop>" is the IOS syntax for a default route.'},
  {cat:'routing',diff:1,q:'What does "O" mean in the routing table?',opts:['Default route','Directly connected','OSPF-learned route','Old/outdated route'],ans:2,explain:'"O" = OSPF. C = connected, S = static, D = EIGRP, R = RIP.'},
  {cat:'routing',diff:1,q:'Which command displays the full routing table?',opts:['show ip interface brief','show ip route','show running-config','show arp'],ans:1,explain:'"show ip route" lists all routes the router knows: connected, static, and dynamically learned.'},
  {cat:'commands',diff:1,q:'What does "no shutdown" do on a router interface?',opts:['Disables it','Enables it','Removes the IP','Resets counters'],ans:1,explain:'Router interfaces are shutdown by default. "no shutdown" enables them.'},
  {cat:'commands',diff:1,q:'Which command shows interface status and IPs in summary?',opts:['show interfaces','show ip route','show ip interface brief','show running-config'],ans:2,explain:'"show ip interface brief" gives a compact table of all interfaces and their status.'},
  {cat:'commands',diff:1,q:'What does "copy running-config startup-config" do?',opts:['Loads saved config','Saves current config to NVRAM','Backs up to TFTP','Compares configs'],ans:1,explain:'Saves the active config to NVRAM — persists across reboots.'},
  {cat:'commands',diff:1,q:'What prompt indicates you are in privileged EXEC mode?',opts:['Router>','Router#','Router(config)#','Router(config-if)#'],ans:1,explain:'> = user EXEC, # = privileged EXEC, (config)# = global config, (config-if)# = interface config.'},
  {cat:'security',diff:1,q:'What does "service password-encryption" do?',opts:['Generates RSA keys','Encrypts all plaintext passwords in the running config','Sets the enable secret','Configures SSH only'],ans:1,explain:'"service password-encryption" applies a weak type-7 cipher to plaintext passwords — use "enable secret" for real security.'},
  {cat:'nat',diff:1,q:'What command shows active NAT/PAT mappings?',opts:['show ip nat statistics','show ip nat translations','show running-config','show ip route'],ans:1,explain:'"show ip nat translations" displays the current table of inside local ↔ inside global ↔ outside address mappings.'},
  // Medium (diff:2)
  {cat:'subnetting',diff:2,q:'What is the network address of 192.168.1.130/26?',opts:['192.168.1.0','192.168.1.128','192.168.1.64','192.168.1.192'],ans:1,explain:'A /26 creates blocks of 64. 130 falls in the block starting at 128.'},
  {cat:'subnetting',diff:2,q:'A /30 subnet is typically used for what type of link?',opts:['Large LAN','WAN point-to-point','Server farm','Wireless access'],ans:1,explain:'/30 gives exactly 2 usable hosts — perfect for connecting two router interfaces.'},
  {cat:'subnetting',diff:2,q:'What is the wildcard mask for /24?',opts:['255.255.255.0','0.0.0.0','0.0.0.255','255.0.0.0'],ans:2,explain:'Wildcard = inverse of subnet mask. /24 = 255.255.255.0 → wildcard = 0.0.0.255.'},
  {cat:'subnetting',diff:2,q:'How many subnets when splitting 192.168.1.0/24 into /26?',opts:['2','4','8','6'],ans:1,explain:'2^(26−24) = 4 subnets of 64 addresses each.'},
  {cat:'subnetting',diff:2,q:'Config shows "192.168.1.128 255.255.255.192". How many usable hosts?',opts:['30','62','64','126'],ans:1,explain:'/26 = 2⁶ = 64 total addresses. Subtract 2 (network + broadcast) = 62 usable host addresses.'},
  {cat:'subnetting',diff:2,q:'A /27 subnet — how many usable host addresses per subnet?',opts:['32','30','14','62'],ans:1,explain:'2⁵ = 32 total addresses − 2 = 30 usable hosts per /27 subnet.'},
  {cat:'vlan',diff:2,q:'What is an SVI?',opts:['A physical switch port','A virtual VLAN gateway on an L3 switch','A WAN serial interface','A loopback address'],ans:1,explain:'SVIs (interface vlan <id>) act as Layer 3 gateways for VLANs on multilayer switches.'},
  {cat:'vlan',diff:2,q:'Which command enables Layer 3 routing on a 3560 switch?',opts:['enable routing','ip routing','switchport routing enable','route enable'],ans:1,explain:'"ip routing" must be enabled before a multilayer switch can route between VLANs.'},
  {cat:'vlan',diff:2,q:'Which command restricts a trunk to carry only VLANs 10, 20 and 30?',opts:['switchport trunk native vlan 10,20,30','switchport trunk allowed vlan 10,20,30','switchport access vlan 10,20,30','vlan trunk permit 10,20,30'],ans:1,explain:'"switchport trunk allowed vlan" replaces the default (all VLANs). Use "add" to append without replacing.'},
  {cat:'routing',diff:2,q:'What is the administrative distance of OSPF?',opts:['90','110','120','1'],ans:1,explain:'AD: Connected=0, Static=1, EIGRP=90, OSPF=110, RIP=120. Lower = more trusted.'},
  {cat:'routing',diff:2,q:'What is the administrative distance of EIGRP?',opts:['90','110','120','1'],ans:0,explain:'EIGRP internal AD = 90. OSPF = 110, RIP = 120. Lower AD = more preferred source.'},
  {cat:'commands',diff:2,q:'What does "no ip domain-lookup" do?',opts:['Disables DNS for clients','Prevents DNS lookup for mistyped commands','Removes the domain name','Disables DHCP'],ans:1,explain:'Without this, mistyped commands trigger a DNS lookup that pauses the CLI for 30+ seconds.'},
  {cat:'commands',diff:2,q:'What information does "show version" display?',opts:['Interface IP addresses','IOS version, uptime, memory, and platform info','Active NAT translations','OSPF neighbor table'],ans:1,explain:'"show version" shows IOS version, router model, RAM/flash size, uptime, config register, and interface count.'},
  {cat:'security',diff:2,q:'What is required before generating RSA keys for SSH?',opts:['An ACL must be applied','Hostname and domain-name must be set','VTY lines must be configured','Enable secret must be set'],ans:1,explain:'"crypto key generate rsa" requires hostname and ip domain-name first.'},
  {cat:'security',diff:2,q:'What does "transport input ssh" on VTY lines do?',opts:['Enables SSH and Telnet','Disables SSH','Allows only SSH — blocks Telnet','Requires a certificate'],ans:2,explain:'Telnet sends credentials in plaintext. SSH only on VTY is basic hardening.'},
  {cat:'security',diff:2,q:'Difference between "enable password" and "enable secret"?',opts:['They are identical','enable secret uses MD5; enable password is plaintext by default','enable password is more secure','enable secret only works on switches'],ans:1,explain:'Always use "enable secret" — MD5-hashed. "enable password" is plaintext unless service password-encryption is set.'},
  {cat:'security',diff:2,q:'Which ACL type filters only on source IP?',opts:['Extended ACL','Named ACL','Standard ACL','Reflexive ACL'],ans:2,explain:'Standard ACLs (1–99) match source IP only. Extended ACLs also match destination, protocol and port.'},
  {cat:'security',diff:2,q:'What does "ip access-class" do when applied to VTY lines?',opts:['Encrypts VTY traffic','Restricts which IPs can open a management session','Sets the SSH key size','Enables AAA authentication'],ans:1,explain:'"ip access-class <acl> in" on VTY lines allows/denies remote management connections based on source IP.'},
  {cat:'nat',diff:2,q:'What does the "overload" keyword enable in a NAT statement?',opts:['Dynamic NAT with a pool','Static one-to-one NAT','PAT — many IPs share one public IP using port numbers','NAT on the outside interface'],ans:2,explain:'"overload" enables Port Address Translation (PAT). Multiple inside hosts share one public IP, differentiated by source port numbers.'},
  {cat:'nat',diff:2,q:'Which interface should have "ip nat inside"?',opts:['The WAN interface facing the ISP','The LAN interface connected to private hosts','The loopback interface',"Any interface — it doesn't matter"],ans:1,explain:'"ip nat inside" marks the private/LAN-facing interface. "ip nat outside" marks the public/WAN-facing interface. Both must be set.'},
  {cat:'nat',diff:2,q:'What type of NAT creates a permanent 1:1 mapping?',opts:['Dynamic NAT','PAT','Static NAT','Overloaded NAT'],ans:2,explain:'Static NAT permanently maps one private IP to one public IP. Used for servers that must always be reachable at a fixed public address.'},
  // Hard (diff:3)
  {cat:'subnetting',diff:3,q:'Find the error: PC has IP 192.168.1.64/26, default gateway 192.168.1.129. What is wrong?',opts:['The IP is a network address','The gateway is in a different subnet','The subnet mask is invalid','Nothing — this is correct'],ans:1,explain:'192.168.1.64/26 → subnet range .64–.127. The gateway .129 is in the .128 block — a different subnet. PCs must use a gateway inside their own subnet.'},
  {cat:'subnetting',diff:3,q:'"show ip int brief" shows 192.168.1.255 assigned to an interface. What is the problem?',opts:['Correct — last host address','This is the broadcast address — not assignable to a host','This is a network address','The address is a multicast'],ans:1,explain:'192.168.1.255 is the broadcast address of a /24. It cannot be assigned to a host interface.'},
  {cat:'subnetting',diff:3,q:'Host IP is 10.10.5.200, mask 255.255.255.192. What is the correct network address?',opts:['10.10.5.0','10.10.5.128','10.10.5.192','10.10.5.224'],ans:2,explain:'/26 = blocks of 64: .0, .64, .128, .192. 200 falls in the block starting at 192. Network = 10.10.5.192.'},
  {cat:'vlan',diff:3,q:'VLAN 10 uses 192.168.10.0/24. A PC in VLAN 10 has gateway 192.168.20.1 and cannot reach the router. What is the problem?',opts:['Wrong subnet mask','Gateway is on a different VLAN subnet','VLAN is not active','Trunk port is missing'],ans:1,explain:'VLAN 10 hosts must use a gateway in the 192.168.10.x range. 192.168.20.1 belongs to VLAN 20 — wrong sub-interface.'},
  {cat:'routing',diff:3,q:'What does "passive-interface" do in OSPF?',opts:['Shuts down the interface','Stops OSPF hellos while still advertising the network','Removes the network from OSPF','Increases OSPF cost'],ans:1,explain:'passive-interface prevents OSPF adjacencies but still advertises the connected network.'},
  {cat:'routing',diff:3,q:'Routing table shows: S* 0.0.0.0/0 [1/0] via 203.0.113.1. What does this mean?',opts:['OSPF default route via 203.0.113.1','Static default route — all unmatched traffic goes to 203.0.113.1','Connected directly to 203.0.113.1','RIP-learned route with cost 1'],ans:1,explain:'"S*" = static default route. [1/0] = AD 1, metric 0. All packets with no more specific match are forwarded to 203.0.113.1.'},
  {cat:'routing',diff:3,q:'OSPF shows a neighbor stuck in 2WAY state on a broadcast segment. Is this a problem?',opts:['Yes — all OSPF neighbors must reach FULL','No — DROther routers stay in 2WAY with each other; only DR/BDR adjacencies reach FULL','Yes — hello timers are mismatched','No — it means the link is passive-interface'],ans:1,explain:'On broadcast networks only DR and BDR form FULL adjacency with all others. DROther routers stay in 2WAY with each other — this is correct and expected behavior.'},
  {cat:'commands',diff:3,q:'ping 8.8.8.8 succeeds but ping google.com fails. What is the first command to run?',opts:['show ip route','show ip interface brief','show ip name-server','show access-lists'],ans:2,explain:'"show ip name-server" reveals which DNS server is configured. IP works but hostname resolution fails.'},
  {cat:'security',diff:3,q:'Traffic is silently dropped. Which command reveals which ACL rules have been matched?',opts:['show ip nat translations','show ip route','show ip access-lists','show vlan brief'],ans:2,explain:'"show ip access-lists" shows each ACL entry with a hit counter — high matches on a deny rule = culprit found.'},
  {cat:'nat',diff:3,q:'Where should an extended ACL be placed for best practice?',opts:['Close to the destination','Close to the source','On the WAN interface only','On the router with the default route'],ans:1,explain:'Extended ACLs close to the source drop unwanted traffic early, saving bandwidth across the network.'},
  {cat:'nat',diff:3,q:'A NAT entry shows: inside local 10.1.1.5:2345 → inside global 203.0.113.10:2345. What type of NAT is this?',opts:['Dynamic NAT (pool-based)','Static PAT — a fixed port mapping for one inside host','PAT (overload) — dynamically assigned port','Static NAT (no port translation)'],ans:1,explain:'A permanent mapping that includes a specific port number is Static PAT — used to allow inbound connections to a specific service on an inside host.'},
  // Nightmare (diff:4)
  {cat:'routing',diff:4,q:'R1 and R2 are OSPF neighbors. The adjacency reaches EXSTART and stays there permanently. No ACL or firewall blocks the link. What is most likely the cause?',opts:['Area ID mismatch','MTU mismatch on the connecting interfaces','Wrong hello/dead timers','Duplicate router IDs'],ans:1,explain:'OSPF EXSTART deadlock means both sides send DBDs but cannot agree on master/slave — almost always an MTU mismatch. One side drops the DBD because it exceeds its ip mtu. Fix: match MTU or use "ip ospf mtu-ignore".'},
  {cat:'vlan',diff:4,q:'Two switches both have bridge priority 32768. SW-A has MAC 0050.7966.0001, SW-B has MAC 0050.7966.000F. Which becomes the STP root bridge?',opts:['SW-B — higher MAC wins STP election','SW-A — lower MAC is the tiebreaker when priority is equal','Whoever was powered on first','The switch with more ports'],ans:1,explain:'STP root = lowest Bridge ID = lowest priority, then lowest MAC. Priority ties at 32768, so compare MACs: 0001 < 000F → SW-A wins.'},
  {cat:'security',diff:4,q:'An extended ACL permits SSH from 10.0.0.0/8 on VTY lines. ICMP (ping) from admin hosts stops working. What single fix restores ICMP without opening broad access?',opts:['Replace with "permit ip any any"','Add "permit icmp any any" before the implicit deny','Remove the ACL from VTY lines','Change to standard ACL'],ans:1,explain:'All ACLs end with an implicit "deny ip any any". ICMP is not TCP — not covered by the SSH permit. Adding "permit icmp any any" above the implicit deny restores ping/traceroute only.'},
  {cat:'routing',diff:4,q:'A /30 WAN link has "ip ospf network broadcast" on both sides. Adjacency forms but reconvergence after a link flap is very slow. What is the root cause?',opts:['The area is stub — LSAs are suppressed','DR/BDR election on a 2-router segment adds wait timers before a new DR is elected','Hello timers are mismatched','The link MTU is too small for LSAs'],ans:1,explain:'Broadcast type causes DR/BDR election. After a flap, the remaining router must wait for dead-interval + election before converging. Fix: "ip ospf network point-to-point" skips election on p2p links.'},
  {cat:'subnetting',diff:4,q:'R1 subinterfaces: Gi0/0.10 = 192.168.1.1/24 (VLAN 10), Gi0/0.20 = 192.168.1.2/24 (VLAN 20). Inter-VLAN routing fails. What is the misconfiguration?',opts:['"encapsulation dot1Q" is missing','Both subinterfaces are in the same /24 subnet — overlapping networks cause a routing conflict','Subinterface numbers must exactly match VLAN IDs','Native VLAN must be on Gi0/0.1'],ans:1,explain:'A router cannot have two interfaces in the same network. Both are in 192.168.1.0/24 — the routing table conflicts and only one wins. VLAN 20 needs its own subnet (e.g. 192.168.20.0/24).'},
  {cat:'nat',diff:4,q:'PAT is configured. An inside host (10.1.1.5) can ping 8.8.8.8. An outside host trying to reach 10.1.1.5 directly fails. Is this a bug?',opts:['Bug — PAT should allow inbound connections too','Expected — PAT only maps outbound sessions; no inbound entry exists until an inside host initiates','The NAT pool is exhausted','Static NAT must also be configured for any PAT to work'],ans:1,explain:'PAT is stateful: entries are created only when an inside host initiates. Unsolicited inbound packets have no matching translation entry and are dropped. To allow inbound, add a static NAT entry.'},
];"""

pattern = r'const QUIZ_QS=\[.*?\];'
new_content = re.sub(pattern, new_quiz, content, flags=re.DOTALL)

if new_content == content:
    print('ERROR: pattern not found or no change')
else:
    with open(r'C:\Users\chris\ciscolearn\www\index.html', 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f'OK: replaced. Original length: {len(content)}, New length: {len(new_content)}')
